[workspace]
members = [
    "apps/cli",
    "apps/desktop/src-tauri",
    "apps/server",
    "crates/db"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Samuel Wahome <hey@samwahome.com>"]
repository = "https://github.com/Samuel-dot-cloud/skopio"
rust-version = "1.80.0"

[workspace.dependencies]
chrono = "0.4.40"
serde = "1.0.218"
tokio = "1.43.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
dirs = "6.0.0"
serde_json = "1.0.140"
log = "0.4.26"
git2 = "0.20.0"
reqwest = "0.12.12"
env_logger = "0.11.6"
anyhow = "1.0.97"
