[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum = "0.8.1"
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "chrono"] }

db = { path = "../../crates/db" }
chrono = { workspace = true, features = ["serde"] }
dirs = { workspace = true }
tower-http = { version = "0.6.2", features = ["cors"] }
