[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.2", features = [] }

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
tauri = { version = "2.1.0", features = ["objc-exception"] }
tauri-plugin-log = "2.0.0-rc"
chrono = { workspace = true, features = ["serde"] }
cocoa = "0.26.0"
core-graphics = "0.24.0"
tokio = { workspace = true, features = ["full", "tracing"] }
core-foundation = "0.10.0"
objc2 = "0.6.0"
strum_macros = "0.27.1"
strum = "0.27.1"
tokei = "12.1.2"
dashmap = "6.1.0"
anyhow = { workspace = true }

db = { path = "../../../crates/db" }
url = "2.5.4"
console-subscriber = "0.4.1"
pprof = { version = "0.14.0", features = ["flamegraph", "frame-pointer", "prost-codec"] }
