[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.29", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["blocking", "json"]}
rusqlite = { version = "0.32.0", features = ["bundled"]}
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0.138"

