name: Build release CLI artifacts

on:
  push:
    branches:
      - release
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

env:
  CLI_PATH: apps/cli
  BIN_NAME: skopio-cli

jobs:
  release-cli:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin

      - name: Setup Apple signing keychain
        shell: bash
        run: |
          set -euo pipefall
          KEYCHAIN=build.keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"

          echo "$MAC_CERT_P12_BASE64" | base64 --decode > cert.p12
          security import cert.p12 -k "$KEYCHAIN" -P "$MAC_CERT_PASSWORD" -t /usr/bin/codesign
          rm -f cert.p12

          security set-key-partition-list -S apple-tool;,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
        env:
          MAC_CERT_P12_BASE64: ${{ secrets.MAC_CERT_P12_BASE64 }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Detect version from Cargo.toml
        id: meta
        shell: bash
        run: |
          set -euo pipefail
          VER=$(cargo metadata --format-version=1 --no-deps --manifest-path "${{ env.CLI_PATH }}/Cargo.toml" \
                | /usr/bin/python3 -c 'import sys,json;print(json.load(sys.stdin)["packages"][0]["version"])')
          TAG="v${VER}"
          # mark prerelease if semver has a hyphen suffix (alpha/beta/rc or any pre tag)
          if [[ "$VER" =~ -([A-Za-z0-9.+-]+)$ ]]; then
            PRERELEASE=true
          else
            PRERELEASE=false
          fi
          echo "version=$VER" >> $GITHUB_OUTPUT
          echo "tag=v$VER" >> $GITHUB_OUTPUT
          echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
          echo "Release $TAG (prerelease=$PRERELEASE)"

      - name: Build aarch64
        working-directory: ${{ env.CLI_PATH }}
        run: cargo build --release --locked --target aarch64-apple-darwin

      - name: Build x86_64
        working-directory: ${{ env.CLI_PATH }}
        run: cargo build --release --locked --target x86_64-apple-darwin

      - name: Sign, zip, notarize, staple, checksums
        id: pkg
        shell: bash
        env:
          DEV_IDENTITY: ${{ secrets.DEV_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          set -euo pipefail
          mkdir -p dist
          TARGET_DIR="${CARGO_TARGET_DIR:-target}"

          sign_bin() {
            local bin="$1"
            codesign --force --options runtime --timestamp --sign "$DEV_IDENTITY" "$bin"
            codesign --verify --verbose=2 "$bin"
            spctl -a -vv -t execute "$bin" || true
          }

          notarize_zip() {
            local zip="$1"
            xcrun notarytool submit "$zip" \
              --apple-id "$APPLE_ID" \
              --team-id "$TEAM_ID" \
              --password "$AC_PASSWORD" \
              --wait

              xcrun stapler staple "$zip" || true
          }

          pack() {
            local arch="$1"
            local cpu
            case "$arch" in
              aarch64-apple-darwin) cpu="aarch64" ;;
              x86_64-apple-darwin)  cpu="x86_64"  ;;
              *) cpu="$arch" ;;
            esac

            local bin="${TARGET_DIR}/${arch}/release/${{ env.BIN_NAME }}"
            local staged="dist/${{ env.BIN_NAME }}-darwin-${cpu}"
            local zip="dist/${{ env.BIN_NAME }}-darwin-${cpu}.zip"

            if [[ ! -f "$bin" ]]; then
              echo "❌ Expected binary not found: $bin"
              ls -la "${TARGET_DIR}/${arch}/release" || true
              exit 1
            fi

            cp "$bin" "$staged"
            strip -S -x "$staged" || true
            sign_bin "$staged"

            (cd dist && zip -q "$(basename "$zip")" "$(basename "$staged")")

            notarize_zip "$zip"

            local sh256; sh256=$(shasum -a 256 "$zip" | awk '{print $1}')
            local size;  size=$(stat -f "%z" "$zip")

            echo "${sh256}  $(basename "$zip")" >> dist/checksums_sha256.txt
            echo "${arch}_zip=$zip"   >> $GITHUB_OUTPUT
            echo "${arch}_sha=$sh256" >> $GITHUB_OUTPUT
            echo "${arch}_size=$size" >> $GITHUB_OUTPUT
          }

          : > dist/checksums_sha256.txt
          pack aarch64-apple-darwin
          pack x86_64-apple-darwin

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        working-directory: ${{ env.CLI_PATH }}
        shell: bash
        run: |
          set -euo pipefail
          VER="${{ steps.meta.outputs.version }}"
          NOTES="$GITHUB_WORKSPACE/${{ env.CLI_PATH }}/RELEASE_NOTES.md"
          CHANGELOG="CHANGELOG.md"
          BODY="$(mktemp)"

          test -f "$CHANGELOG" || { echo "Missing $CHANGELOG"; exit 1; }

          # Match headings like: "## 1.2.3", "## v.1.2.3", "## [1.2.3]", "## [v1.2.3] ..."
          awk -v ver="$VER" '
            BEGIN {
              patv = "^##[[:space:]]*\\[?v?" ver "\\]?([[:space:]-]|$)"
              insec=0
            }
            $0 ~ patv { insec=1; next }         # start after the heading line
            insec && /^##[[:space:]]*\[?v?[0-9]/ { insec=0 }  # stop at next version section
            insec { print }
          ' "$CHANGELOG" > "$BODY" || true

          if ! [ -s "$BODY" ]; then
            echo "No changelog section found for version $VER in CHANGELOG.md" >&2
            exit 1
          fi

          {
            echo "# Changelog"
            echo
            cat "$BODY"
          } > "$NOTES"

          echo "notes_file=$NOTES" >> "$GITHUB_OUTPUT"

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: "v${{ steps.meta.outputs.version }}"
          prerelease: ${{ steps.meta.outputs.prerelease }}
          body_path: ${{ steps.changelog.outputs.notes_file }}
          files: |
            ${{ steps.pkg.outputs.aarch64-apple-darwin_zip }}
            ${{ steps.pkg.outputs.x86_64-apple-darwin_zip }}
            dist/checksums_sha256.txt

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.9.2
        with:
          cosign-release: "v2.5.3"

      - name: Cosign sign artifacts
        env:
          COSIGN_EXPERIMENTAL: "1"
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist/signatures
          sign() {
            local file="$1" base; base=$(basename "$file")
            cosign sign-blob --yes "$file" \
              --output-signature "dist/signatures/$base.sig" \
              --output-certificate "dist/signatures/$base.cert" \
              --bundle "dist/signatures/$base.bundle"
          }
          sign "${{ steps.pkg.outputs.aarch64-apple-darwin_zip }}"
          sign "${{ steps.pkg.outputs.x86_64-apple-darwin_zip }}"

      - name: Upload signatures to Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          files: dist/signatures/*

      - name: Attach latest.json
        if: ${{ steps.meta.outputs.prerelease != 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          OWNER_REPO="${{ github.repository }}"
          TAG="${{ steps.meta.outputs.tag }}"
          VER="${{ steps.meta.outputs.version }}"
          FILE_ARM="$(basename "${{ steps.pkg.outputs.aarch64-apple-darwin_zip }}")"
          FILE_X64="$(basename "${{ steps.pkg.outputs.x86_64-apple-darwin_zip }}")"
          BASE="https://github.com/${OWNER_REPO}/releases/download/${TAG}"
          cat > latest.json <<EOF
          {
            "version": "$VER",
            "released_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "assets": {
              "darwin-aarch64": {
              "url": "$BASE/$FILE_ARM",
              "sha256": "${{ steps.pkg.outputs.aarch64-apple-darwin_sha }}",
              "size": ${{ steps.pkg.outputs.aarch64-apple-darwin_size }},
              "sig": {
                "type": "cosign",
                "signature_url": "$BASE/signatures/$FILE_ARM.sig",
                "certificate_url": "$BASE/signatures/$FILE_ARM.cert",
                "bundle_url": "$BASE/signatures/$FILE_ARM.bundle"
             }
           },
           "darwin-x86_64": {
             "url": "$BASE/$FILE_X64",
             "sha256": "${{ steps.pkg.outputs.x86_64-apple-darwin_sha }}",
             "size": ${{ steps.pkg.outputs.x86_64-apple-darwin_size }},
             "sig": {
               "type": "cosign",
               "signature_url": "$BASE/signatures/$FILE_X64.sig",
               "certificate_url": "$BASE/signatures/$FILE_X64.cert",
               "bundle_url": "$BASE/signatures/$FILE_X64.bundle"
             }
            }
           }
          }
          EOF
          gh release upload "${TAG}" latest.json --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
