name: Release Selector

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Which release(s) to run"
        type: choice
        options: [cli, server, both]
        required: true
        default: cli
      tag:
        description: "Optional override tag (passed through)"
        required: false
        default: ""

permissions:
  contents: read
  id-token: write

jobs:
  guard:
    uses: ./.github/workflows/_guard-release-branch.yml
    with:
      branch: release

  run-cli:
    needs: guard
    if: ${{ github.event.inputs.target == 'cli' || github.event.inputs.target == 'both' }}
    uses: ./.github/workflows/cli-release.yml
    with:
      tag: ${{ github.event.inputs.tag}}
    secrets: inherit

  run-server:
    needs: guard
    if: ${{ github.event.inputs.target == 'server' || github.event.inputs.target == 'both'}}
    uses: ./.github/workflows/server-release.yml
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets: inherit
